Do not create a tmp dir until it's needed. Add fallback tmp dirs and check if mktemp works.

diff --git a/parallely b/parallely
--- a/parallely
+++ b/parallely
@@ -131,11 +131,11 @@ CMD_SHELL_ARGS="${CMD_SHELL_ARGS-${DEFAULT_CMD_SHELL_ARGS}}"
 SHOW_CMD_OUTPUT_CMD_ARGS="${SHOW_CMD_OUTPUT_CMD_ARGS-$SHOW_CMD_OUTPUT_CMD_ARGS_DEFAULT}"
 SHOW_CMD_OUTPUT_CMD="${SHOW_CMD_OUTPUT_CMD-$SHOW_CMD_OUTPUT_CMD_DEFAULT}"
 
-if [ -z "${PARALLELY_TMP_DIR-}" ]; then
-  require_command mktemp "or set \$PARALLELY_TMP_DIR"
-fi
-
-PARALLELY_TMP_DIR="${PARALLELY_TMP_DIR-$(mktemp -d)}"
+# PARALLELY_TMP_DIR requires complex initialization and that is done after
+# creating the logging/error functions
+MK_TEMP="${MK_TEMP-mktemp}"
+# --directory doesn't work on MacOS
+MK_TEMP_ARGS="${MK_TEMP_ARGS--d}"
 
 SHOW_LINE_COUNT="${SHOW_LINE_COUNT-true}"
 SHOW_BYTE_COUNT="${SHOW_BYTE_COUNT-true}"
@@ -314,6 +314,43 @@ bytes_to_human_readable() {
 # bytes_to_human_readable 1121551421
 # bytes_to_human_readable 11215514210000000
 
+############## Initialize a base tmp directory.
+# This code must run before parsing the name/command arguments because the tmp dir
+# is used to store commands, as we cannot use bash arrays to store arguments
+# that may contain whitespace and have no hash maps to relate a name to its
+# command
+#
+# The script can run if only given arguments like --help or --show-configuration
+
+make_fallback_tmp_directory() {
+  log "Trying fallback: $1"
+  local TEST_FILE="$1/parallely-tmp-test-$(whoami)"
+  if touch "$TEST_FILE"; then
+    PARALLELY_TMP_DIR="$1"
+  else
+    error "Unable to touch file in $1: $TEST_FILE"
+    return 1
+  fi
+}
+
+set_or_make_base_tmp_directory() {
+  if [ -z "${PARALLELY_TMP_DIR-}" ]; then
+    debug "Creating a tmp directory"
+    require_command "$MK_TEMP" "or set \$PARALLELY_TMP_DIR"
+    PARALLELY_TMP_DIR="$("$MK_TEMP" "$MK_TEMP_ARGS" || true)"
+    if [ -z "${PARALLELY_TMP_DIR-}" ]; then
+      log "Parallely requires a tmp dir to parse its arguments."
+      error "Unable to make a directory with $MK_TEMP $MK_TEMP_ARGS"
+      log "Please set \$PARALLELY_TMP_DIR"
+      log "Will try to use a common base directory for temporary files"
+      make_fallback_tmp_directory /tmp || make_fallback_tmp_directory $HOME/tmp || \
+        ( error "Unable to make a tmp directory. Please set \$PARALLELY_TMP_DIR". ; \
+          exit "$NO_TMP_DIRECTORY_EXIT_CODE"
+        )
+    fi
+  fi
+}
+
 ############## Help
 help() {
   # I tried changing this to one large multi-line string, but it messes with
@@ -394,9 +431,11 @@ help() {
   echo "        Arguments for command for printing stderr and stdout of a command"
   echo "        Default: $SHOW_CMD_OUTPUT_CMD_ARGS_DEFAULT"
   echo "    --tmp-dir or set \$PARALLELY_TMP_DIR:"
-  echo "        If you don't have \`mktemp\` on your system, you must set this"
+  echo "        If you don't have $MK_TEMP on your system, you must set this"
   echo "        option with the environment variable!"
-  echo "        Default: created using \'mktemp\'"
+  echo "        Note: $SCRIPT_NAME usually needs a tmp directory to parse its arguments!"
+  echo "        Alternative: set \$MK_TEMP and \$MK_TEMP_ARGS"
+  echo "        Default: created using $MK_TEMP"
   echo "    --line-count|--no-line-count or set \$SHOW_LINE_COUNT:"
   echo "        Whether to show line count."
   echo "        Default: true"
@@ -712,29 +751,40 @@ if [ "$#" = 0 ]; then
 fi
 
 # Used to handle the --tmp-dir argument
-make_readable_tmp_dir() {
+make_cmd_out_dir() {
+  # Try to have a human readable suffix in the directory name
   if command -v whoami > /dev/null && command -v date > /dev/null; then
     TMP_DIR_SUFFIX="-$(whoami)-$(date +%Y-%m-%d)"
   else
     error whomai or date not installed
     TMP_DIR_SUFFIX=
   fi
+
   CMD_OUT_DIR="$PARALLELY_TMP_DIR/$SCRIPT_NAME-logs$TMP_DIR_SUFFIX"
+
+  # Erase any existing files
+  # Useful when using a fixed base directory like /home/tmp
   if [ -d "$CMD_OUT_DIR" ]; then
     debug WARNING Temporary directory exists. Deleting "$CMD_OUT_DIR"
     rm -rf "$CMD_OUT_DIR"
   fi
-  if [ -n "${ORIGINAL_CMD_OUT_DIR-}" ]; then
-    mv "$ORIGINAL_CMD_OUT_DIR/" "$CMD_OUT_DIR/"
-  fi
+
+  # These are used in case the --tmp-dir argument is passed
   ORIGINAL_CMD_OUT_DIR="$CMD_OUT_DIR"
   ORIGINAL_TMP_DIR="$PARALLELY_TMP_DIR"
+
+  # Create directory
   mkdir -p "$CMD_OUT_DIR"
 }
 
-make_readable_tmp_dir
+move_old_cmd_out_dir() {
+  if [ -n "${ORIGINAL_CMD_OUT_DIR-}" ]; then
+    mv "$ORIGINAL_CMD_OUT_DIR/" "$CMD_OUT_DIR/"
+  fi
+}
+
 # Make sure to move this file if passed the --tmp-dir argument!
-NAMES_FILE="$CMD_OUT_DIR/names"
+NAMES_FILE="__UNINITIALIZED__"
 debug "arglog: Will parse ($#) arguments:"
 for arg in "$@"; do
   debug "arglog: Argument \"$arg\""
@@ -794,7 +844,13 @@ while [ "$#" -gt 0 ]; do
   fi
 
   # Check for repeated names
-  if [ -f "$NAMES_FILE" ]; then
+  if ! [ -f "$NAMES_FILE" ]; then
+    # Create tmp directory!
+    set_or_make_base_tmp_directory
+    make_cmd_out_dir
+    verbose Created tmp directory at "$CMD_OUT_DIR"
+    NAMES_FILE="$CMD_OUT_DIR/names"
+  else
     if grep "^$CURRENT_NAME$" "$NAMES_FILE" 2>&1 > /dev/null; then
       error "Duplicate name $CURRENT_NAME detected. Please rename."
       exit "$REPEATED_NAME_EXIT_CODE"
@@ -815,13 +871,6 @@ done
 
 if [ "$SHOW_PIDS" = true ] && [ "$FORCE_SEQUENTIAL" = true ]; then
   error "Will not show PIDs when --sequential is set"
-fi
-
-# Handle the --tmp-dir argument
-if ! [ "$ORIGINAL_TMP_DIR" = "$PARALLELY_TMP_DIR" ]; then
-  make_readable_tmp_dir
-  COMMAND_FILE="$CMD_OUT_DIR/$CURRENT_NAME.command"
-  NAMES_FILE="$CMD_OUT_DIR/names"
 fi
 
 show_debug_info
@@ -865,7 +914,7 @@ show_configuration() {
   log "FORCE_SEQUENTIAL=$FORCE_SEQUENTIAL"
   log "SHOW_CMD_OUTPUT_CMD=$SHOW_CMD_OUTPUT_CMD"
   log "SHOW_CMD_OUTPUT_CMD_ARGS=$SHOW_CMD_OUTPUT_CMD_ARGS"
-  log "PARALLELY_TMP_DIR=$PARALLELY_TMP_DIR"
+  log "PARALLELY_TMP_DIR=${PARALLELY_TMP_DIR-(unset! Haven\'t created a tmp dir yet)}"
   log "SHOW_LINE_COUNT=$SHOW_LINE_COUNT"
   log "SHOW_BYTE_COUNT=$SHOW_BYTE_COUNT"
   log "HUMAN_READABLE_BYTE_COUNT=$HUMAN_READABLE_BYTE_COUNT"
@@ -877,7 +926,7 @@ show_configuration() {
   log "LIGHT_MODE=$LIGHT_MODE"
   log "SHOW_CONFIGURATION=$SHOW_CONFIGURATION"
   log "SHOW_PIDS=$SHOW_PIDS"
-  log "Temporary directory CMD_OUT_DIR=$CMD_OUT_DIR"
+  log "Temporary directory CMD_OUT_DIR=${CMD_OUT_DIR-(unset!)}"
   log
 }
 
@@ -896,6 +945,14 @@ if ! [ -f "$NAMES_FILE" ]; then
   fi
 else
   NUM_CMDS="$(cat "$NAMES_FILE" | wc -l)"
+fi
+
+# Handle the --tmp-dir argument
+if ! [ "$ORIGINAL_TMP_DIR" = "$PARALLELY_TMP_DIR" ]; then
+  make_cmd_out_dir
+  move_old_cmd_out_dir
+  COMMAND_FILE="$CMD_OUT_DIR/$CURRENT_NAME.command"
+  NAMES_FILE="$CMD_OUT_DIR/names"
 fi
 
 ############## Print message before running all commands
